### ISSUE TITLE
TypeError: components.map is not a function

### ISSUE THREAD

**Issue by hongbo-miao** [gdi2290/ng-conf-2016-universal-patterns#2]
After `npm install` and run **1-events-demo** by `npm start`, got the error:

> /ng-conf-2016-universal-patterns/1-events-demo/node_modules/angular2-universal/dist/node/bootloader.js:243
>         var directives = components.map(function (component) {
>                                     ^
> 
> TypeError: components.map is not a function
>     at Bootloader._applicationAll (/ng-conf-2016-universal-patterns/1-events-demo/node_modules/angular2-universal/dist/node/bootloader.js:243:37)
>     at Bootloader.serializeApplication (/ng-conf-2016-universal-patterns/1-events-demo/node_modules/angular2-universal/dist/node/bootloader.js:75:21)
>     at readContent (/ng-conf-2016-universal-patterns/1-events-demo/node_modules/angular2-express-engine/dist/src/engine.js:69:41)
>     at /ng-conf-2016-universal-patterns/1-events-demo/node_modules/angular2-express-engine/dist/src/engine.js:94:20
>     at /ng-conf-2016-universal-patterns/1-events-demo/node_modules/graceful-fs/graceful-fs.js:78:16
>     at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3)
> [nodemon] app crashed - waiting for file changes before starting...

**Comment by hongbo-miao** [comment]
The other two demos got same error too.

**Comment by PatrickJS** [comment]
hey, thanks for the issue. add these deps and npm install again
    "angular2-universal-polyfills": "~0.4.1",
    "angular2-express-engine": "0.11.1",
    "angular2-hapi-engine": "0.11.1",

**Comment by hongbo-miao** [comment]
@gdi2290 works perfect now! and thanks for your all amaaaaaaaazing work for Angular 2 ecosystem!
